### ISSUE TITLE
Crash with python 3.10

### ISSUE THREAD

**Issue by cisc0disco** [ebokai/particle_game_of_life#1]
`❯ python3 particle_gol_main.py
Target N: 400 | N: 399
Force Distance: 4.5
Force Strength: 5.0
Friction Strength: 10.0
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/matplotlib/cbook/__init__.py", line 287, in process
    func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/matplotlib/animation.py", line 907, in _start
    self._init_draw()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/matplotlib/animation.py", line 1698, in _init_draw
    self._drawn_artists = self._init_func()
  File "/Users/josefmaly/particle_game_of_life/particle_gol_main.py", line 12, in init
    particles.set_offsets([])
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/matplotlib/collections.py", line 564, in set_offsets
    (np.asarray(self.convert_xunits(offsets[:, 0]), 'float'),
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed`

**Comment by ebokai** [comment]
Any additional information? Did you run the code directly from the source or did you make any changes?

**Comment by ebokai** [comment]
Should be fixed now, in `init()`, specifically `set_offsets` expects to be initialized with a Nx2 array. Might break compatibility with older version of python or matplotlib.
